### ISSUE TITLE
[bug] Error while rendering html/template:index.html

### ISSUE THREAD

**Issue by yoshikawa** [Nagatani/Memorandum#1]
hugoでビルドするとエラーが生じる.
hugoのバージョンアップによる弊害の恐れ有り.

|言語/FW|Version|
|:--|--:|
|go|1.10.3|
|hugo|0.42.1|

【対処法】
`theme/_default/list.html`の内容を`index.html`に移行する.

**Comment by Nagatani** [comment]
PRマージで解決したので、Closeしますー
